# Generated by Django 4.2.20 on 2025-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '일반 사용자')], default='user', max_length=10),
        ),
    ]
