services:
  db:
    container_name: Django_Main
    image: postgres:16
    restart: always
    volumes:
      - local_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Django_Main
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: securepassword
      PGDATA: /var/lib/postgresql/data/Django_Main/
    ports:
      - "54322:5432"

  backend:
    container_name: Django_backend
    build: .
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: Django_nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles

volumes:
  local_db: