# Generated by Django 4.2.21 on 2025-05-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_type', models.CharField(choices=[('EMOTION', '감정 소통'), ('QUESTION', '질문'), ('NOTICE', '공지 사항')], max_length=20)),
                ('ref_id', models.IntegerField(db_column='ref_id')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
