# Generated by Django 4.2.20 on 2025-05-14 20:19


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_expense', models.IntegerField()),
                ('total_income', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monthly_statistic',
            },
        ),
    ]
