# Generated by Django 4.2.20 on 2025-05-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCategory',
            fields=[
                ('wallet_category_type', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('wallet_category_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'wallet_category',
            },
        ),
        migrations.CreateModel(
            name='WalletEmotion',
            fields=[
                ('wallet_emotion_type', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('wallet_emotion_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'wallet_emotion',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('EXPENSE', '지출'), ('INCOME', '수입')], max_length=40)),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.walletemotion')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.walletcategory')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
    ]
