# Generated by Django 4.2.20 on 2025-05-14 20:19


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeview',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticelike',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='notice.notice'),
        ),
        migrations.AddField(
            model_name='noticelike',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='noticeview',
            constraint=models.UniqueConstraint(fields=('user', 'notice'), name='unique_user_notice_view'),
        ),
        migrations.AddConstraint(
            model_name='noticelike',
            constraint=models.UniqueConstraint(fields=('user', 'notice'), name='unique_user_notice_like'),
        ),
    ]
