# Generated by Django 4.2.20 on 2025-05-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='notice_id',
            new_name='id',
        ),
    ]
